### ISSUE TITLE
Admin 페이지를 위한 sdp_admin 앱 생성 및 기본 설정

### ISSUE THREAD

**Issue by sejongk** [sdp-tech/SASM_BE#129]
## Description
- Admin 페이지를 개발할 sdp_admin 앱 생성 및 기본 설정

## To-Do
- [x] sdp_admin 앱 생성
- [x] sdp_admin 하위 urls.py 생성
- [x] sdp_admin 앱 settings.py에 추가
