### ISSUE TITLE
settings.py local, prod 분리하기

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#132]
## Description
- crud를 구현하는 과정에서 local 에서 사용하는 db와 prod에서 사용하는 db 를 분리해야하는 상황이 발생했다.

## To-Do
- [x] settings 폴더 생성 후 base,local,prod 파일 생성
- [x] manage.py와 wsgi.py 에서 파일 설정 변경
- [x] local에 db sqlite로 변경

## ETC
[https://wikidocs.net/75556](url)
[https://blaize.tistory.com/56](url)
