### ISSUE TITLE
모델 변경(PlacePhoto, Place)

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#138]
## Description
- 장소 사진을 기존 URL Field에서 Image Field로 변경(media로 user에게서 사진을 받는 것으로 변경되기 때문)
- 장소 위/경도 값을 기존 left_coordinate, right_coordinate 에서 직관적인 이름 latitude, longitude로 변경
- Place distance 값 삭제
## To-Do
- [x] s3 경로 재설정 
  **media 로 user에게 받는 url**
  media/places/{장소이름}/{timestamp}.{ext} 
  **기존에 있던 사진 url**
  media/places/{장소이름}/1.{ext} 
  media/places/{장소이름}/2.{ext} 
  media/places/{장소이름}/3.{ext} 
  media/places/{장소이름}/rep.{ext} 
- [x] Model에서 PlacePhoto, Place의 reppic URL Field로 변경
- [x] excel 파일로 장소 db 저장하는 /places/save_place code 변경
- [x] serializer와 views에서 latitude, longitude로 이름 변경하기
