### ISSUE TITLE
Place admin sns create, update

### ISSUE THREAD

**Issue by yxnxx** [sdp-tech/SASM_BE#155]
## Description
- Place admin에서 create, update 할 때 sns 정보까지 포함하도록 하기

## To-Do
- [x] 이미 존재하는 snstype일 때는 snsurl 생성 혹은 update
- [x] 존재하지 않는 snstype을 직접 입력한 경우 snstype 생성 후 snsurl 생성
- [x] 삭제한 sns가 있다면 db에서 삭제
