### ISSUE TITLE
배포 환경 설정

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#172]
## Description
- github actions, docker, gunicorn, nginx 를 활용한 배포
- kubernetes 환경으로 전환

#### Phase 1 (CI 단계 완성)
- [x] Github Actions workflow에서 코드 integration 후 컨테이너 이미지 빌드 및 AWS ECR에 push
- [x] Github Actions workflow에서 Actions secrets을 docker compose .env 파일로 생성, docker-compose.yml에서 .env 파일을 컨테이너 환경변수로 설정
- [x] 현재 코드 내 secret들을 환경 변수로부터 가져오도록 변경

#### Phase 2 (Secret 관리 개선)
- [x] Actions secrets을 AWS parameter store로 이관
- [x] EC2 실행 시 IAM 역할을 attach하고, EC2에서 새 이미지 배포 시 AWS parameter store에서 secrets을 가져와 .env 파일 생성 => EC2 서버를 병행 사용하지 않을 것이므로 해당 작업 수행하지 않음

#### Phase 3 (EKS, ArgoCD, GitOps)
- [x] AWS parameter store 내 secret을 AWS EKS Secret으로 mount해 EKS 파드의 환경 변수로 attach
- [x] GitOps를 위한 k8s 매니페스트(.yaml) Git 저장소 사용
- [ ] ArgoCD 도구를 이용한 CD 파이프라인 구축
- [ ] Github Actions와 ArgoCD 연동

**Comment by yxnxx** [comment]
github secrets에서 access key not found 문제 발생. ssh private key를 다음과 같이 등록해야 함. https://farhan-tanvir.medium.com/ci-cd-from-github-to-aws-ec2-using-github-action-e18b621c0507

**Comment by sejongk** [comment]
### 컨테이너 기반 배포 및 운영 환경 구축을 위한 추가 작업 필요
구체적으로 현재 Github Actions이 사실상 CI, CD에 모두 관여하고 있다고 볼 수 있다. 하지만, 향후 Kubernetes 환경으로 전환 시 Github Actions이 Kubernetes 환경에 대한 CD에 필요한 기능을 제공하고 있다고 보기는 어렵다.
따라서 점진적으로 현재 Github Actions에서 CD의 작업을 분리해내어, CI 역할만을 수행하도록 구축하는 과정이 필요하다. 최종적으로 Github Actions는 코드를 기반으로 컨테이너 이미지를 만들고 레지스트리에 push하는 작업까지만 수행하게 될 것이다.

#### Phase 1 (CI 단계 완성)
- [ ] Github Actions workflow에서 코드 integration 후 컨테이너 이미지 빌드 및 AWS ECR에 push
- [ ] Github Actions workflow에서 Actions secrets을 docker compose .env 파일로 생성, docker-compose.yml에서 .env 파일을 컨테이너 환경변수로 설정
- [ ] 현재 코드 내 secret들을 환경 변수로부터 가져오도록 변경

#### Phase 2 (Secret 관리 개선)
- [ ] Actions secrets을 AWS parameter store로 이관
- [ ] EC2 실행 시 IAM 역할을 attach하고, EC2에서 새 이미지 배포 시 AWS parameter store에서 secrets을 가져와 .env 파일 생성

#### Phase 3 (EKS, ArgoCD, GitOps)
- [ ] AWS parameter store 내 secret을 AWS EKS Secret으로 mount해 EKS 파드의 환경 변수로 attach
- [ ] k8s 매니페스트(.yaml) Git 저장소 사용, ArgoCD 도구를 이용한 CD 파이프라인 구축, GitOps로의 전환

**Comment by sejongk** [comment]
> Kubernetes 환경으로 전환 시, 기존 EC2 환경을 테스트용 환경으로 유지, 사용

테스트용 환경을 EC2 대신 Kubernetes에서 테스트 전용 namespace에 구축 예정

**Comment by sejongk** [comment]
@lina1919 @yxnxx 아래 작업 처리 완료
* Actions secrets을 AWS parameter store로 이관
* AWS parameter store 내 secret을 AWS EKS Secret으로 mount해 EKS 파드의 환경 변수로 attach
* GitOps를 위한 k8s 매니페스트(.yaml) Git 저장소 생성
* SASM deployment 생성 완료

**Comment by sejongk** [comment]
쿠버네티스 클러스터 운영 비용 문제로 보류. 향후 쿠버네티스 도입 필요 시 재검토
