### ISSUE TITLE
노션 에러 목록 BE에서 수정

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#193]
## Description
- sdp 학회원들이 작성해준 에러 목록에서 BE에서 수정해야할 부분

## To-Do
- [x] 회원가입 시 alert 문구 수정
- [ ] 회원 정보 수정 시 닉네임 중복 확인
- [ ] 회원 정보 수정 시 이메일 수정 방지

## ETC
추후 삭제/추가 가능
