### ISSUE TITLE
회원가입 시 추가 정보 입력 기능 추가

### ISSUE THREAD

**Issue by sejongk** [sdp-tech/SASM_BE#253]
## Description
- 사용자 맞춤형 서비스 제공을 위한 추가 정보 입력 기능 추가 필요
- 시안 - https://docs.google.com/presentation/d/1zUp-9T414C_EKkx6R7I52QKNtGyq47YnE19GEuadm9g/edit#slide=id.g15fad4c90ae_0_29

## To-Do
- [ ] 추가 정보 model 작성
- [ ] 향후 머신러닝 적용 시 데이터 가공이 용이할 수 있는 구조 논의 필요
- [ ] 추가 정보 api 작성, 소셜 로그인 회원까지 연동될 수 있도록 작성

## ETC
users app 하위가 아닌 별도 app으로 분리해, 해당 정보만 전담해서 입력받고, 가공하도록 모듈화하는 방식에 대하여 논의 필요

**Comment by sejongk** [comment]
제안: 현재 SNS type model과 같이 Place 카테고리, Vegan 카테고리를 별도 model로 만들고, Place, Vegan을 필드로 갖는 model들이 `ForeignKey`나 `ManyToManyField`로 연결
필요성: 
- Place, Vegan 카테고리를 필드로 갖는 모델마다 개별적으로 카테고리 문자열 목록(enum)을 가져야하는 구조 개선
- ForeignKey와 같이 model의 연관 관계 기반으로 한 DB 쿼리 기능 활용(comma와 같은 delimiter 사용 불필요)
