### ISSUE TITLE
코드 품질 향상 작업 수행

### ISSUE THREAD

**Issue by sejongk** [sdp-tech/SASM_BE#298]
## Description
- 코드 전반에 대해 View, Serializer에 위치한 비즈니스 로직을 Service layer로 이관하여 리팩토링
- 핵심 Model, Service, API(View), Serializer에 대해 단위 테스트 작성
- 배포 파이프라인에 테스트 수행 작업 추가

## To-Do
- [ ] Community에 단위 테스트 도입
- [ ] Place 비즈니스 로직을 Service layer로 이관
- [ ] Story 비즈니스 로직을 Service layer로 이관

## ETC
- Ref. https://github.com/HackSoftware/Django-Styleguide
