### ISSUE TITLE
큐레이션 신기능 작업

### ISSUE THREAD

**Issue by yew00n** [sdp-tech/SASM_BE#350]
## Description
- 큐레이션 1차 신기능 구현 작업

## To-Do
- [x] 큐레이션 모델 생성
- [x] LikeApi 구현
- [x] 스토리 모델 수정
- [x] 큐레이션 상세페이지 구현: 지도 및 큐레이션 기본 정보
- [x] 큐레이션 상세페이지 구현: 스토리 정보
- [x] 큐레이션 상세정보 임시 설정(홈화면 노출, 대표 설정, 공개 설정)

## 보류
- [ ] 작성 시 임시저장
- [ ] 팔로워한 유저 큐레이션 목록 보기
- [ ] 큐레이션 검수(홈화면 노출여부, 대표 설정여부, 공개여부)

## ETC
지도 이미지 관련 네이버 API 문서 - https://api.ncloud-docs.com/docs/ai-naver-mapsstaticmap-raster

**Comment by sejongk** [comment]
보류 작업 구현 시 reopen
