### ISSUE TITLE
커뮤니티 신기능 구현

### ISSUE THREAD

**Issue by sejongk** [sdp-tech/SASM_BE#354]
## Description
- 지속가능성 관련 정보글 제공 커뮤니티로의 컨셉 전환
- 웹에서 서비스 중인 기존 커뮤니티 운영에 영향을 주지 않도록 유지하며 신기능 추가

## To-Do
- [x] 로그인한 유저에게만 읽기가 허용되던 것을 모두에게 허용
- [x] 커뮤니티 모델 변경, CRUD API에 반영
- [x] 정보글 통합 검색 
- [ ] 유저 팔로우 관련 기능 - 유저 팔로우하기, 팔로잉 글 보기 등
- [ ] 나만의 카테고리 설정하기
- [ ] 글쓴이 정보 자기 소개 설정하기(마이페이지), 보여주기
- [ ] 글쓴이 다른 글 목록 보여주기
- [ ] 작성하기 기타 옵션 (공개하기, 댓글 기능, 조회수 숨기기)
- [ ] 이 글을 본 사용자들이 본 다른 글 제안
- [ ] 다양한 게시글 조회 및 정렬 옵션 - 사용자 유형별(관리자/일반인/팔로잉), 추천 게시글, 맞춤 게시글

## ETC
- 빅카테고리 및 세부 카테고리 항목 정리
  - TBD
- 설계 및 구현 방식 정리
  - 게시판 분류 -> 빅카테고리, 세부 카테고리 -> Post 내 category 필드 추가
  - 팔로우 -> User 모델에 `follows` 필드 추가
  - 장소 위치 표시 지도 이미지 API: https://api.ncloud-docs.com/docs/ai-naver-mapsstaticmap-raster#%EC%9A%94%EC%B2%AD-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0
  - 장소 -> 좌표 변환 API: https://apis.map.kakao.com/web/sample/keywordList/
  - 통합 검색 - unified 검색 타입을 추가해, 해쉬태그, 카테고리, 제목, 내용 등에 관련 내용이 포함되어 있으면 다 출력
