### ISSUE TITLE
mypage 새로 구현해야 하는 기능 

### ISSUE THREAD

**Issue by KJA000** [sdp-tech/SASM_BE#366]
## Description
- mypage 새로 구현해야 하는 기능 및 api

## To-Do
- [x] 각 팔로워/팔로잉 프로필 사진, 이름, 소개 get @KJA000 
- [x] 팔로워/팔로잉 삭제 기능 delete @KJA000 
- [x] 팔로워/팔로잉 검색 기능 get @KJA000 
- [ ] 큐레이션/내가 좋아요 누른 큐레이션->api @yew00n 
- [x] 프로필 정보에 성별 정보 추가 - 프로필 수정 시 post @KJA000 
- [x] 소개글 작성 post @KJA000 
- [x] story/편집하기 @kjiyun 
- [x] 장소/내가 리뷰 쓴 장소->api @SeoJimin1234 
- [ ] 큐레이션/내가 댓글 쓴 큐레이션->api @yew00n 

-------보류
- [ ] 설정 - 알림 설정 / 공지사항 / 자주 묻는 질문 / 약관 관련 
- [ ] 선호 카테고리 get / 수정 시 post (맞춤정보 설정) ****보류
- [ ] 관심 있는 키워드 get / 수정 시 post (맞춤정보 설정) ****보류
- [ ] 정보글/내가 좋아요 누른 정보글->api
