### ISSUE TITLE
큐레이션 기능추가에 따른 스토리 API 수정

### ISSUE THREAD

**Issue by yew00n** [sdp-tech/SASM_BE#372]
## Description
- 큐레이션 신기능 구현을 위해 기존 스토리 API 일부 수정이 필요

## To-Do
- [x] 모델: address 필드(OneToOne) -> place 필드(FK)
- [x] address 쓰던 로직 모두 place로 대체

- [x] 모델: StoryPhoto에 Story 필드(FK) 추가 
- [x] StoryCreateApi: Story 객체 생성 ->  StoryPhoto 객체 FK 연결
- [x] StoryUpdateApi, StoryDeleteApi

- [x] Sdp_admin의 StoryCreate/Update/Delete Api를 Story앱으로 전환
- [ ] 관련 웹 프런트 코드 수정
