### ISSUE TITLE
User앱 리팩토링

### ISSUE THREAD

**Issue by yew00n** [sdp-tech/SASM_BE#403]
## To-Do
- [x] 소셜로그인, serializer @sejongk 
- [x] base_view @kjiyun 
- [x] pw_change @yew00n
