### ISSUE TITLE
Story Detail 기능 추가

### ISSUE THREAD

**Issue by kjiyun** [sdp-tech/SASM_BE#469]
## Description
- 스토리 detail 기능 추가 필요

## To-Do
- [x] 스토리 detail에서 좋아요 count
- [x] 스토리 detail에서 댓글 count
- [x] 스토리 댓글 좋아요 기능 추가
